### ISSUE TITLE
Working with dynamic ROI setup utilizing mvsdk.py 

### ISSUE THREAD

**Issue by UrFavouriteB0i** [dddomodossola/nastroprint#1]
Hey, I know it's been years since you upload this project, but I wonder have you tried to set ROI dynamically while the camera thread is working? I find it difficult since i get an unknown error while setting the ROI at the weirdest rectangle shape (ex: setting the ROI at 118x350px) using the `mvsdk.setImageResolution(camera, pImageResolution)`.

I notice with the manufacturers camera app, it gives dialogue box "parameter invalid and use adapted setting?" but I don't find any adapted settings in mvsdk.py file

**Comment by dddomodossola** [comment]
Hello @UrFavouriteB0i , 

I never tried changing ROI dynamically. Maybe they found it difficult to handle different buffer sizes [create, copy, destroy] while image grab is running.
I don't have that hardware anymore, so I cannot test it unfortunately. 
I hope my code can be useful for you. Have a nice day

**Comment by UrFavouriteB0i** [comment]
Thank you for your response, @dddomodossola 

No problem, as of today I already figure it out on how to do it using the mvsdk library with several trial and error. This project is really useful to me for my final project on how to use the custom function within the sdk and the GUI application, because there are not much of a project using this mvsdk library, and one of them luckily, is yours. cheers!
